version: "3.8"

services:
  mysql:
    image: mysql:8.2
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: new-api
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:latest
    container_name: redis
    restart: always
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  new-api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: new-api
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
    ports:
      - "3000:3000"
    volumes:
      - ./data:/data               # your working dir inside container
      - ./logs:/app/logs
      - ./.env:/data/.env          # <-- mount your .env where godotenv expects it
    environment:
      - SQL_DSN=root:123456@tcp(mysql:3306)/new-api?parseTime=true
      - REDIS_CONN_STRING=redis://redis:6379/0
      - TZ=Asia/Shanghai

volumes:
  mysql_data:
